import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const domainArticles = [
  'domain/README',
  'domain/done-criteria',
  'domain/execute-agent',
  'domain/verify-agent',
  'domain/harness',
  'domain/harness-testing',
  'domain/agent-queue',
  'domain/agent-supervisor',
  'domain/task-scheduling',
  'domain/sse-hub',
  'domain/persistence',
  'domain/task-events',
  'domain/cycle-commits',
  'domain/worktrees-and-branches',
  'domain/workspace-repo',
  'domain/project-context',
  'domain/runner-adapters',
  'domain/cursor-session-resume',
  'domain/resume-continuation',
  'domain/retry-start-over',
  'domain/retry-resume',
  'domain/observability-trace-lines',
  'domain/testing',
];

const adrArticles = [
  'adr/ADR-0001-project-context',
  'adr/ADR-0002-flatten-task-hierarchy',
  'adr/ADR-0003-verify-component-upgrade',
  'adr/ADR-0004-verdicts-on-the-db',
  'adr/ADR-0005-extract-agent-harness',
  'adr/ADR-0006-phase-boundary-resume',
  'adr/ADR-0007-parent-completion-via-criteria',
  'adr/ADR-0008-dependency-satisfies-epic-scheduling',
  'adr/ADR-0009-awaiting-subtasks-status',
  'adr/ADR-0010-remove-subtasks',
  'adr/ADR-0011-remove-task-type',
  'adr/ADR-0012-structured-verify-commands',
  'adr/ADR-0013-prompt-automations',
  'adr/ADR-0014-cycle-commit-tracking',
  'adr/ADR-0015-dual-retry-modes',
  'adr/ADR-0016-observe-vs-admit-commits',
  'adr/ADR-0017-harness-internal-domains',
  'adr/ADR-0018-harness-orchestration-fsm',
  'adr/ADR-0019-agentworker-internal-layout',
  'adr/ADR-0020-realtime-sse-layout',
  'adr/ADR-0021-harness-execute-orchestration',
  'adr/ADR-0022-task-sync-policy',
  'adr/ADR-0023-task-scheduling-domain',
  'adr/ADR-0024-task-create-flow-slice',
  'adr/ADR-0025-frontend-data-coherence',
  'adr/ADR-0026-backend-data-coherence',
  'adr/ADR-0027-stream-idle-evidence-recovery',
  'adr/ADR-0028-in-cycle-verify-only-retry',
  'adr/ADR-0029-funclogmeasure-category-driven',
  'adr/ADR-0030-attempt-phase-correlation',
  'adr/ADR-0031-cursor-session-resume-default',
  'adr/ADR-0032-agent-claimed-commit-index',
  'adr/ADR-0033-git-worktrees-and-branches',
  'adr/ADR-0034-opt-in-schema-migration',
  'adr/ADR-0035-docusaurus-documentation-site',
];

const sidebars: SidebarsConfig = {
  hamixSidebar: [
    'guide',
    {
      type: 'category',
      label: 'Get started',
      collapsed: false,
      link: {type: 'doc', id: 'get-started/index'},
      items: ['get-started/index', 'execute-and-verify', 'docker'],
    },
    {
      type: 'category',
      label: 'Understand the system',
      collapsed: false,
      link: {type: 'doc', id: 'architecture'},
      items: ['architecture', 'data-model', 'configuration'],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      items: ['web', 'agent-map', ...domainArticles.filter((id) =>
        ['domain/harness', 'domain/harness-testing', 'domain/execute-agent', 'domain/verify-agent', 'domain/testing'].includes(id),
      )],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['api', 'naming', 'omitted-features', 'guide'],
    },
    {
      type: 'category',
      label: 'Deep dives',
      collapsed: true,
      link: {type: 'doc', id: 'domain/README'},
      items: domainArticles,
    },
    {
      type: 'category',
      label: 'Architecture decisions',
      collapsed: true,
      items: adrArticles,
    },
  ],
};

export default sidebars;
